name: "Sync Issue Field"
description: "Sync GitHub parent issue's fields to child issue's fields."
author: "kudoas"
branding:
  color: green
  icon: shield
inputs:
  repository:
    description: "Repository name with owner. For example, kudoas/sync-issue-field. Default is the current repository."
    default: ${{ github.repository }}
  issue:
    description: "The number that identifies the issue. Specify the child issue you wish to synchronize with the parent issue. Default is the current issue."
    default: ${{ github.event.issue.number }}
  token:
    description: "GitHub Token"
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/dist/app
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_REPOSITORY: ${{ inputs.repository }}
        GITHUB_ISSUE: ${{ inputs.issue }}
