name: Build and Create PR for Binary
on:
  pull_request:
    paths-ignore:
      - '*.md'
      - 'renovate.json'
      - '.env.sample'
      - '.github/workflows/*.yml'
      - 'dist/app'

permissions:
  contents: write
  pull-requests: write

jobs:
  build_and_create_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Build binary
        run: |
          CGO_ENABLED=0 go build -ldflags="-w -s" -v -o app ./cmd/run
          mkdir -p dist
          mv app dist/
      - name: Check for changes
        id: check_diff
        run: git diff --exit-code
        continue-on-error: true
      - name: Create Pull Request
        if: steps.check_diff.outcome == 'failure'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat: Update built binary in dist/"
          title: "Build: Update binary for PR #${{ github.event.pull_request.number }}"
          body: |
            This PR updates the built binary in `dist/` based on the changes in #${{ github.event.pull_request.number }}.

            Auto-generated by GitHub Actions.
          branch: update-binary-pr-${{ github.event.pull_request.number }}
          base: ${{ github.event.pull_request.head.ref }}
          add-paths: |
            dist/
