name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run release-please
        uses: google-github-actions/release-please-action@e4dc86ba9405554aeba3c6bb2d169500e7d3b4ee # v4
        id: release
        with:
          release-type: go
          token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Build and Commit Binary, Push to origin
        run: |
          CGO_ENABLED=0 go build -ldflags="-w -s" -v -o app ./cmd/run
          mkdir -p dist
          mv app dist/

          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add dist/app
          git status
          git commit -m "Build and update binary" || echo "No changes to commit"
          git push origin HEAD

