name: Sync Issue Fields

on:
  issues: 
    types: [opened, edited, labeled, unlabeled]

permissions:
  issues: write
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Use Sync Issue Field Action
        uses: kudoas/sync-issue-field@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
